apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: test-topic
  namespace: confluent
spec:
  kafkaRest:
    authentication:
      type: basic
      basic:
        roles:
          - Administrators
        secretRef: rest-credential
    tls:
      enabled: true
  replicas: 3
  partitionCount: 3
  configs:
    cleanup.policy: "delete"

