apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: test-topic
  namespace: confluent
spec:
  replicas: 3
  partitionCount: 3
  configs:
    cleanup.policy: "delete"
  kafkaClusterRef:
    name: kafka
  kafkaRest:
    authentication:
      type: bearer
      bearer:
        secretRef: rest-credential
---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: test-topic2
  namespace: confluent
spec:
  replicas: 1
  partitionCount: 3
  configs:
    cleanup.policy: "delete"
  kafkaClusterRef:
    name: kafka
  kafkaRest:
    authentication:
      type: bearer
      bearer:
        secretRef: rest-credential
