apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: test-topic
  namespace: confluent
spec:
  kafkaRestClassRef:
    name: default
  replicas: 3
  partitionCount: 3
  configs:
    cleanup.policy: "delete"

