apiVersion: platform.confluent.io/v1beta1
kind: Connect
metadata:
  name: connect
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-server-connect:7.6.2
    init: confluentinc/confluent-init-container:2.9.1
  tls:
    secretRef: tls-group
  authorization:
    type: rbac
  build:
    type: onDemand 
    onDemand:
      plugins:
        confluentHub:
          - name: kafka-connect-datagen
            owner: confluentinc
            version: 0.6.3
        locationType: confluentHub
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.confluent.svc.cluster.local:9071
      authentication:
        type: plain
        jaasConfig:
          secretRef: credential
      tls:
        enabled: true
    mds:
      endpoint: https://kafka.confluent.svc.cluster.local:8090
      tokenKeyPair:
        secretRef: mds-token
      authentication:
        type: bearer
        bearer:
          secretRef: connect-mds-client
      tls:
        enabled: true
  configOverrides:
    log4j:
      - log4j.rootLogger=INFO, stdout, connectAppender
      - log4j.logger.org.apache.kafka.connect=INFO
      - log4j.appender.connectAppender=org.apache.log4j.RollingFileAppender
      - log4j.appender.connectAppender.MaxFileSize=5MB
      - log4j.appender.connectAppender.MaxBackupIndex=3
      #- log4j.appender.connectAppender.File=/mnt/dataconnect/$POD_NAME/log/connect-distributed.log
      - log4j.appender.connectAppender.File=/var/log/kafka/connect-distributed.log
      - log4j.appender.connectAppender.layout=org.apache.log4j.PatternLayout
    server:
      - config.storage.replication.factor=1
      - offset.storage.replication.factor=1
      - status.storage.replication.factor=1
      - config.storage.topic=test.connect-configs
      - offset.storage.topic=test.connect-offsets
      - status.storage.topic=test.connect-status
      
  #mountedVolumes:
  #  volumes:
  #    - name: pv-connect-logs
  #      persistentVolumeClaim:
  #        claimName: connect-logs-claim
  #  volumeMounts:
  #    - mountPath: "/mnt/dataconnect"
  #      name: pv-connect-logs
  podTemplate:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
    probe:
      liveness:
        periodSeconds: 10
        failureThreshold: 5
        timeoutSeconds: 500 
    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
      runAsNonRoot: true  
