apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent
spec:
  replicas: 3
  license:
    globalLicense: true
  image:
    application: confluentinc/cp-server:7.7.1
    init: confluentinc/confluent-init-container:2.9.3
  tls:
    #secretRef: kafka-tls
    secretRef: tls-group
  listeners:
    internal:
      authentication:
        type: ldap
        jaasConfig:
          secretRef: kafka-ldap-credentials
      tls:
        enabled: true
    external:
      authentication:
        type: ldap
      tls:
        enabled: true
      externalAccess:
        type: staticForHostBasedRouting
        staticForHostBasedRouting:
          domain: ncapelle-playground.confluent.io
          port: 443
  authorization:
    type: rbac
    superUsers:
      - User:kafka
  
  configOverrides:
    server:
      - "confluent.license.topic.replication.factor=1"
      - "confluent.metrics.reporter.topic.replicas=1"
      - "confluent.tier.metadata.replication.factor=1"
      - "confluent.metadata.topic.replication.factor=1"
      - "confluent.balancer.topic.replication.factor=1"
      - "confluent.security.event.logger.exporter.kafka.topic.replicas=1"
      - "event.logger.exporter.kafka.topic.replicas=1"
      - "offsets.topic.replication.factor=1"
    log4j:
      - log4j.logger.io.confluent.rest-utils=DEBUG, stdout
      - log4j.additivity.io.confluent.rest-utils=false
      - log4j.logger.io.confluent.rbacapi=DEBUG, stdout
      - log4j.additivity.io.confluent.rbacapi=false
      - log4j.logger.io.confluent.tokenapi=DEBUG, stdout
      - log4j.additivity.io.confluent.tokenapi=false
      - log4j.logger.io.confluent.security.auth=DEBUG, stdout
      - log4j.additivity.io.confluent.security.auth=false
      - log4j.logger.io.confluent.security.store=DEBUG, stdout
      - log4j.additivity.io.confluent.security.store=false
      - log4j.logger.io.confluent.common.security.jetty=DEBUG, stdout
      - log4j.additivity.io.confluent.common.security.jetty=false
      - log4j.logger.io.confluent.security.auth.provider.ldap=TRACE, stdout
  services:
    mds:
      tls:
        enabled: true
      tokenKeyPair:
        secretRef: mds-token
      provider:
        type: ldap
        ldap:
          address: ldap://ldap.confluent.svc.cluster.local:389
          authentication:
            type: simple
            simple:
              secretRef: credential
          configurations:
            groupNameAttribute: cn
            groupObjectClass: posixGroup
            groupMemberAttribute: memberUid
            groupMemberAttributePattern: cn=(.*),ou=users,dc=test,dc=com
            groupSearchBase: ou=groups,dc=test,dc=com
            groupSearchScope: 2
            userNameAttribute: cn
            #userMemberOfAttributePattern: CN=(.*),DC=test,DC=com
            userObjectClass: '*'
            userSearchBase: dc=test,dc=com
            #userSearchFilter: (|(dn=cn=*,ou=users,dc=test,dc=com)(objectClass=organizationalRole))
            userSearchFilter: (|(objectClass=inetOrgPerson)(objectClass=organizationalRole))
            userSearchScope: 2
  dependencies:
    kafkaRest:
      authentication:
        type: bearer
        bearer:
          secretRef: mds-client
    kRaftController:
      clusterRef:
        name: kcontroller
        namespace: confluent
      controllerListener:
        tls:
          enabled: true
        authentication:
          type: ldap
          jaasConfig:
            secretRef: kafka-ldap-credentials
  dataVolumeCapacity: 10Gi
  podTemplate:
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
      runAsNonRoot: true
  metricReporter:
    enabled: true
    tls:
      enabled: true
    authentication:
        type: plain
        jaasConfig:
          secretRef: credential
---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestClass
metadata:
  name: default
  namespace: confluent
spec:
  kafkaRest:
    authentication:
      type: bearer
      bearer:
        secretRef: rest-credential
