apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestClass
metadata:
  name: default
  namespace: confluent
spec:
  kafkaRest:
    kafkaClusterRef:
      name: kafka
    kafkaRest:
      authentication:
        type: basic
        basic:
          secretRef: rest-credential
          file: basic.txt
      tls:
        enabled: true