apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent
spec:
  dependencies:
    kRaftController:
      controllerListener:
        tls:
          enabled: true
        authentication:
          type: plain
          jaasConfig:
            secretRef: credential
      clusterRef:
        name: kraftcontroller
  dataVolumeCapacity: 1G
  image:
    application: docker.io/confluentinc/cp-server:7.7.2
    init: confluentinc/confluent-init-container:2.9.4
  tls:
    secretRef: kafka-tls
    jksPassword:
      secretRef: kafka-credential-tls
  replicas: 3