apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent
spec:
  license:
    secretRef: confluent-license
  dependencies:
    kRaftController:
      controllerListener:
        tls:
          enabled: true
        authentication:
          type: plain
          jaasConfig:
            secretRef: credential
      clusterRef:
        name: kraftcontroller
  dataVolumeCapacity: 1G
  image:
    application: docker.io/confluentinc/cp-server:7.7.2
    init: confluentinc/confluent-init-container:2.9.4
  listeners:
    internal:
      tls:
        enabled: true
      authentication:
        type: plain
        jaasConfig:
          secretRef: credential-jaas
  configOverrides:
    server:
      - kafka.rest.enable=true
      - auto.create.topics.enable=true
      - default.replication.factor=3
      - min.insync.replicas=2
      - num.partitions=3
      - log.retention.hours=48
      - confluent.cluster.link.enable=false
      - confluent.telemetry.enabled=false
      - authorizer.class.name=org.apache.kafka.metadata.authorizer.StandardAuthorizer
      - super.users=User:kafka;User:kraft;User:kraftcontroller;User:operator
    log4j:
      - log4j.logger.kafka.server.link=INFO, stdout
  tls:
    secretRef: kafka-tls
    jksPassword:
      secretRef: kafka-credential-tls
  replicas: 3