apiVersion: platform.confluent.io/v1beta1
kind: KRaftController
metadata:
  name: kraftcontroller
  namespace: confluent
spec:
  license:
    secretRef: confluent-license
  dataVolumeCapacity: 1G
  image:
    application: docker.io/confluentinc/cp-server:7.9.0
    init: confluentinc/confluent-init-container:2.11.0
  listeners:
    controller:
      tls:
        enabled: true
      authentication:
        type: plain
        jaasConfig:
          secretRef: credential
  configOverrides:
    server:
      - auto.create.topics.enable=true
      - default.replication.factor=3
      - min.insync.replicas=2
      - num.partitions=3
      - log.retention.hours=48
      - confluent.cluster.link.enable=false
      - confluent.telemetry.enabled=false
      - confluent.balancer.enable=false
      - authorizer.class.name=org.apache.kafka.metadata.authorizer.StandardAuthorizer
      - super.users=User:kafka;User:kraft;User:kraftcontroller;User:operator
    log4j:
      - log4j.logger.kafka.server.link=INFO, stdout
  tls:
    secretRef: kafka-tls
    jksPassword:
      secretRef: kafka-credential-tls
  replicas: 3