apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-acl-script
  namespace: confluent
  labels:
    app: kafka-acl
data:
  acl-setup.sh: |
    #!/bin/bash

    ACL_FILE=/tmp/acl-config.yaml
    BROKER="${KAFKA_BROKER:-broker:9092}"

    echo "Using Kafka Broker: $BROKER"

    # Parse YAML and process each ACL block
    while IFS= read -r line; do
      case "$line" in
        "  - name:"*)  # Detect ACL block start
          if [[ -n "$NAME" ]]; then
            # Apply ACL for the previous block
            echo "Processing ACL: $NAME"
            for topic in "${TOPICS[@]}"; do
              CMD="kafka-acls --bootstrap-server $BROKER --command-config /tmp/admin.properties $ACTION --allow-principal $ALLOW_PRINCIPAL"
    
              # Add operations
              for op in "${OPERATIONS[@]}"; do
                CMD+=" --operation $op"
              done
    
              # Add topic and resource pattern type
              CMD+=" --topic $topic"
              CMD+=" --resource-pattern-type $RESOURCE_PATTERN_TYPE"
    
              # Add transactional ID if present
              if [[ -n "$TRANSACTIONAL_ID" ]]; then
                CMD+=" --transactional-id $TRANSACTIONAL_ID"
              fi
    
              echo "Executing: $CMD"
              eval "$CMD"  # Execute the command
            done
          fi
          # Reset variables for new block
          NAME=$(echo "$line" | sed -E 's/.*name: *//')
          ACTION=""
          ALLOW_PRINCIPAL=""
          TRANSACTIONAL_ID=""
          RESOURCE_PATTERN_TYPE=""
          OPERATIONS=()
          TOPICS=()
          ;;
        "    action:"*)  # Extract action
          ACTION=$(echo "$line" | sed -E 's/.*action: *//')
          ;;
        "    allow_principal:"*)  # Extract allow_principal
          ALLOW_PRINCIPAL=$(echo "$line" | sed -E 's/.*allow_principal: *//')
          ;;
        "    transactional_id:"*)  # Extract transactional_id
          TRANSACTIONAL_ID=$(echo "$line" | sed -E 's/.*transactional_id: *//')
          ;;
        "    resource_pattern_type:"*)  # Extract resource_pattern_type
          RESOURCE_PATTERN_TYPE=$(echo "$line" | sed -E 's/.*resource_pattern_type: *//')
          ;;
        "      - "*)
          item=$(echo "$line" | sed -E 's/.*- *//')
          if [[ -n "$lastKey" ]]; then
            case "$lastKey" in
              "operations")
                OPERATIONS+=("$item")
                ;;
              "topics")
                TOPICS+=("$item")
                ;;
            esac
          fi
          ;;
        "    operations:"*)  # Operations block start
          lastKey="operations"
          ;;
        "    topics:"*)  # Topics block start
          lastKey="topics"
          ;;
      esac
    done < "$ACL_FILE"

    # Process the last ACL block after finishing the loop (this part is crucial for a single ACL)
    if [[ -n "$NAME" ]]; then
      echo "Processing final ACL: $NAME"
      for topic in "${TOPICS[@]}"; do
        CMD="kafka-acls --bootstrap-server $BROKER --command-config /tmp/admin.properties $ACTION --allow-principal $ALLOW_PRINCIPAL"

        for op in "${OPERATIONS[@]}"; do
          CMD+=" --operation $op"
        done

        CMD+=" --topic $topic"
        CMD+=" --resource-pattern-type $RESOURCE_PATTERN_TYPE"

        if [[ -n "$TRANSACTIONAL_ID" ]]; then
          CMD+=" --transactional-id $TRANSACTIONAL_ID"
        fi

        echo "Executing: $CMD"
        eval "$CMD"  # Execute the command
      done
    fi
