apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-acl-config
  namespace: confluent
  labels:
    app: kafka-acl
data:
  acl-config.yaml: |
    kafka-acls:
      - action: "--add"
        allow-principal: "User:team1"
        operations:
          - "READ"
          - "DESCRIBE"
        topic: "mytopic"
        resource-pattern-type: "literal"
      
      - action: "--add"
        allow-principal: "User:team1"
        operations:
          - "READ"
          - "DESCRIBE"
        topic: "mytopic"
        resource-pattern-type: "literal"