apiVersion: v1
kind: Secret
metadata:
  name: kafka-admin-secret
  namespace: confluent
  labels:
    app: kafka-acl
type: Opaque
data:
  admin.properties: |
    IyBTZWN1cml0eSBQcm90b2NvbCBhbmQgQXV0aGVudGljYXRpb24gTWVjaGFuaXNtCnNlY3VyaXR5LnByb3RvY29sPVNBU0xfU1NMCnNhc2wubWVjaGFuaXNtPVBMQUlOCgojIFBhdGhzIHRvIFRydXN0c3RvcmUgYW5kIEtleXN0b3JlCnNzbC50cnVzdHN0b3JlLmxvY2F0aW9uPS92YXVsdC9zZWNyZXRzL3RydXN0c3RvcmUuamtzCnNzbC50cnVzdHN0b3JlLnBhc3N3b3JkPW15c3RvcmVwYXNzd29yZAoKCiMgU0FTTCBDb25maWd1cmF0aW9uIChmb3IgUExBSU4gYXV0aGVudGljYXRpb24pCnNhc2wuamFhcy5jb25maWc9b3JnLmFwYWNoZS5rYWZrYS5jb21tb24uc2VjdXJpdHkucGxhaW4uUGxhaW5Mb2dpbk1vZHVsZSByZXF1aXJlZCBcCiAgICB1c2VybmFtZT0ia2Fma2EiIFwKICAgIHBhc3N3b3JkPSJrYWZrYS1zZWNyZXQiOw==