apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/topics
- ../../base/rolebindings
patches:
- target:
    kind: KafkaTopic
    name: test-topic
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
