apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: kafka-sr
spec:
  clustersScopeByIds:
    schemaRegistryClusterId: id_schemaregistry_confluent
  principal:
    name: kafka
    type: user
  resourcePatterns:
  - name: "*"
    patternType:  LITERAL
    resourceType: Subject
  role: ResourceOwner